
name: Windows

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

env:
  VCPKG_VERSION: "2021.05.12"


jobs:


    x64-windows:
      runs-on: windows-2019
      steps:
        - name: "Setting long paths"
          run: git config --system core.longpaths true     
        - name: "Clone vcpkg"
          uses: actions/checkout@v2
          with:
            repository: Microsoft/vcpkg
            path: vcpkg
            ref: ${{ env.VCPKG_VERSION }}
            submodules: true
            lfs: true
        - name: "Bootstrap vcpkg"
          run: bootstrap-vcpkg.bat
          working-directory: vcpkg
        - name: "Install vcpkg"
          run: vcpkg integrate install
          working-directory: vcpkg
        - name: "Update vcpkg"
          run: vcpkg update
          working-directory: vcpkg
        - name: "Build gtk:x64-windows"
          run: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && vcpkg install gtk:x64-windows
          working-directory: vcpkg
          shell: cmd
        - name: Export gtk:x64-windows
          run: vcpkg export gtk:x64-windows --zip --output=GTK_x64_VS2019
          working-directory: vcpkg
        - name: Create release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: x64-windows
            prerelease: false
            title: "x64-windows"
            files: vcpkg\GTK_x64_VS2019.zip
          if: github.event_name != 'pull_request'